### ISSUE TITLE
[SOLVED] Sidr JS Menu not working under Midnight.js?

### ISSUE THREAD

**Issue by DylanOpet** [Aerolab/midnight.js#31]
Been battling with this plugin as it seems that sidr menu button works until midnight is initiated.

DEMO: http://bit.ly/1Nclrch

Try clicking menu when loaded, it works, then scroll down and it starts midnights new header class, now it doesn't. Any good way of fixing this issue? Tried looking around in console and everywhere but cant seem to find why it wont work.

**Comment by RobertoGonzalez** [comment]
That's because midnight creates multiple copies of the header, and Sidr seems to be bound only to the first #side-menu it can find. When you scroll to another section, an identical copy of the button appears, but since it's a copy without any click handlers, the button no longer seems to work. This may or may not be a bug.

A simple fix for this is just handling the click higher up on the dom (in the header, for instance), and then catching only the .menu-button events. For instance:

``` js
$('header').on('click', '.menu-button', function(event){ /* Handle the click */ });
```

**Comment by DylanOpet** [comment]
Ah, makes sense! Thanks again mate.
