### ISSUE TITLE
How to change the Header Title?

### ISSUE THREAD

**Issue by abhiklodh** [Aerolab/midnight.js#36]
Lame question - i tried editing the midnight.js website(of aerolab obviously) and had a hard time changing the title (you know the "MIDNIGHT.JS" with a moon) to my choice but in vain.

Really accept some help.
Ty ahead

**Comment by abhiklodh** [comment]
I need help on generating the image the way it is actually there in the site
logo.png file. (sorry can't upload it)

**Comment by RobertoGonzalez** [comment]
@abhiklodh You can use pretty much any valid HTML for the header. The logo in http://aerolab.github.io/midnight.js/ is actually implemented as a background for the a.logo element (styles.css:118), and that's why you aren't seeing any markup. 
It's done that way to load a single (quite large) image and cycle through all the available logos with background-position. It's to make the site load a tiny bit faster but you don't necessarily have to do that for the plugin to work.

You can do the same thing but instead of messing with background-position you can just change the background-image for each header instead.
