### ISSUE TITLE
Elementary OS, Google Chrome, Only one header appears.

### ISSUE THREAD

**Issue by dakoon2003** [Aerolab/midnight.js#4]
I am getting no errors in the console, but as I scroll down the first header disappears but nothing replaces it.

**Comment by tomByrer** [comment]
@dakoon2003: Chrome that you installed from the Ubuntu repo via eOS's package manager, or their own <s>bastardized version</s> fork of WebKit/Safari, [Midori](http://midori-browser.org/), which has little to do with Chrome now since Blink?  (I tried eOS a month ago, but they & Midori seem slow to update.)

If it is Chrome, then testing on Chrome in Ubuntu would be best.  If it Midori, then perhaps polyfills might help.

**Comment by dakoon2003** [comment]
Its actual Chrome (Midori is useless) downloaded and installed from Google itself. I will do some digging and see if I can get you some more info on it.

**Comment by tomByrer** [comment]
Works for me in Win7 Chrome 38.0.2125.77 beta-m (64-bit).
If I get around to installing the Kubuntu Plasma 5 beta, I'll look on there for you.

**Comment by dakoon2003** [comment]
Version 37.0.2062.120 (64-bit) Here are my chrome specs I will download and troubleshoot

**Comment by dillinghamio** [comment]
The example page isn't changing for me

> Uncaught ReferenceError: $section is not defined

**Comment by RobertoGonzalez** [comment]
This was probably fixed on the last update. Let me know if it's still an issue.
