### ISSUE TITLE
problem in safari

### ISSUE THREAD

**Issue by Khangeldy** [Aerolab/midnight.js#49]
I have a problem, after include mightnight.js . Му animations based on scroll  in safari shakes.

**Comment by RobertoGonzalez** [comment]
@Khangeldy Do you have a live example for this? 
One of the known issues for this library (specially on OSX) is that unless the site is running at a perfect 60fps you'll notice some minor shearing when scrolling. This usually happens if the site is complex or has too many animations going on at the same time, as the requestAnimationFrame method can't catch up to the native scrolling and ends up lagging behind a frame or two.

**Comment by Khangeldy** [comment]
@RobertoGonzalez  If you have Mac Os x  please visit this [codepen](http://codepen.io/Khangeldy/pen/wWMWoM).There no any hard animations, i think main problem is scroll based animation not correct work. Simple  `el.style.transform = "translateY(" + window.scrollY + "px)";` code in MacOSX shaking.

Thanks!

**Comment by Khangeldy** [comment]
I guess problem appearance only retina display or MacOSx
