### ISSUE TITLE
Logo doesn't appear back after scrolling back to top of the page

### ISSUE THREAD

**Issue by amichel86** [Aerolab/midnight.js#70]
Hello and thanks for you plugin!

I noticed on Edge, when I scroll passed my first "midnight" section and come back to the top of the page, sometimes the logo doesn't appear. It is a strange bug that doesn't happen all the time. Would you happen to know a fix and or an alternative plugin?

It happens on your demo page on Edge too.

https://youtu.be/_TtlsxD8lTY

Thanks!

**Comment by RobertoGonzalez** [comment]
Hi @amichel86! 
It seems it's a bug with Edge and multiple nested transforms (which we use to clip the different headers). From what I can tell, when the inner transform goes to 110%, some of the inner layers seem to get corrupted and they either become transparent or randomly show other parts of the site.

I'd take a stab in the dark and guess it's some sort of underlying GPU OOM issue with Edge, so if you really need this to work I'd try disabling transforms [by forcing the _getSupportedTransform method to return false on Edge](https://github.com/Aerolab/midnight.js/blob/gh-pages/midnight.jquery.js#L115) and seeing if that helps.

Since Edge has relatively few users and they are going to switch to Webkit soon I personally wouldn't worry too much about this bug, since their rendering engine is going to be phased out pretty soon. 
If you can get it to work I'd be happy to accept a PR though.

**Comment by amichel86** [comment]
@RobertoGonzalez I'm kind of a JS noob, can you explain a little further how I can have the _getSupportedTransform function return false on Edge? Thanks!

**Comment by RobertoGonzalez** [comment]
@amichel86 Matching the browser's user agent to the [MS Edge User Agent](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string) should work. I believe it's the `Edg/` keyword you should look for.
